name: Build

on:
  push:
    branches: [ staging ]
    paths:
      - ProjectBorealis.uproject
      - Source/**
      - .github/workflows/build.yml

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 4320
    runs-on: [self-hosted, windows, x64, working]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.REPO_TOKEN }}
          clean: false
          lfs: true
      - name: Download LFS assets
        run: |
          git-lfs checkout
          git-lfs prune
      - name: Update Engine
        run: |
          .\PBSync.exe --sync engine
      - name: Clean Binaries
        run: |
          try { Remove-Item -Path Binaries -Recurse -ErrorAction stop }
          catch [System.Management.Automation.ItemNotFoundException] { $null }
      - name: Build
        run: |
          .\PBSync.exe --build source
      - name: Version
        run: |
          .\PBSync.exe --autoversion hotfix
      - name: Package
        run: |
          .\PBSync.exe --build package
      - name: Commit and Push
        run: |
          git config user.name "Project Borealis"
          git config user.email "info@projectborealis.com"
          git commit -am "chore(version): hotfix release from $Env:GITHUB_SHA"
          git pull
          git push
      - name: Release
        run: |
          .\PBSync.exe --build release
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
      - name: Inspect All
        run: |
          .\PBSync.exe --build inspectall
        continue-on-error: true
