name: main -> trunk

on:
  push:
    branches: [ main ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge main -> trunk
      uses: everlytic/branch-merge@master
      with:
        target_branch: trunk
        github_token: ${{ secrets.REPO_TOKEN }}
