name: promoted -> main

on:
  push:
    branches: [ staging ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge staging -> main
      uses: everlytic/branch-merge@master
      with:
        target_branch: main
        github_token: ${{ secrets.REPO_TOKEN }}
